name: K6 Load Test with HTML Report

on:
  push:
    branches:
      - main

jobs:
  k6_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install K6
      run: |
        sudo apt update
        sudo apt install -y gnupg software-properties-common
        sudo gpg --keyserver keyserver.ubuntu.com --recv-keys 33D40BC6
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt update
        sudo apt install -y k6

    - name: Run K6 Test and generate HTML report
      run: k6 run LoginTest.js

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: k6-html-report
        path: summary.html
